### Install Python modules
### Install .py files and config
### Setup Systemd 

### Generate  arole

- hosts: all
  remote_user: pi
  become: yes
  gather_facts: false
  vars:    

  tasks:
# Install python packages.
    - pip:
        name: pynmea2,pyserial,configparser,RPi.bme280,smbus2
        executable: pip3
  

    - name: Copy usb rules 
      copy:
        src: ./files/99-usb.rules
        dest: /etc/udev/rules.d/ 
        owner: root
        group: dialout
        mode: 0644
        backup: yes

    - name: Copy nmeaHp33a
      copy:
          src: "{{ item }}"
          dest: /home/midnite
          owner: midnite
          mode: 0644
      with_fileglob:
           ['../nmeaHP33A/*.config','../nmeaHP33A/*.py']

    - name: Copy nmeaComm
      copy:
          src: "{{ item }}"
          dest: /home/midnite
          owner: midnite
          mode: 0644
      with_fileglob:
           ['../nmeaComm/*.config','../nmeaComm/*.py']

    - name: Copy nmeaBMP280
      copy:
          src: "{{ item }}"
          dest: /home/midnite
          owner: midnite
          mode: 0644
      with_fileglob:
           ['../nmeaBMP280/*.config','../nmeaBMP280/*.py']
#           ./files/*.py

    - name: Copy services 
      copy:
          src: "{{ item }}"
          dest: /etc/systemd/system
          owner: root
          mode: 0755
      with_fileglob:
           ./files/*.service

#    - name: Copy the service files into the system service directory
#      copy: src=./files/*.service dest=/etc/systemd/system owner=root group=root mode=0755

    - name: just force systemd to reread configs (2.4 and above)
      systemd:
        daemon_reload: yes

    - name: enable nmeacomm service
      service: name=nmea-comm enabled=yes

    - name: start nmeacomm
      service: name=nmea-comm state=started
