### Install Python modules
### Install .py files and config
### Setup Systemd 

### Generate  arole

- hosts: all
  remote_user: pi
  become: yes
  gather_facts: false
  vars:    

  tasks:
# Install python packages.
    - pip:
        name: pynmea2,pyserial,configparser,RPi.bme280,smbus2
        executable: pip3
  

 	- name: Copy usb rules 
      copy:
        src: ./files/99-usb.rules
        dest: /etc/udev/rules.d/ 
        owner: root
        group: dialout
        mode: 0644
        backup: yes
        
    - name: Copy config files to boot
       copy:
        src: ./files/*.config
        dest: /boot/
        owner: midnite
        group: midnite
        mode: 0644
        backup: yes   

    - name: Copy python files to home
       copy:
        src: ./files/*.py
        dest: /home/midnite/
        owner: midnite
        group: midnite
        mode: 0644
        backup: yes   
