### Install Python modules
### Install .py files and config
### Setup Systemd 

- hosts: all
  remote_user: pi
  become: yes
  gather_facts: false
  vars:    

  tasks:
# Install (Bottle) python package.
    - pip:
        name: pynmea2,pyserial,configparser,RPi.bme280,smbus2
        executable: pip3
  

    


